### ISSUE TITLE
CPU Settings not working

### ISSUE THREAD

**Issue by bigbear22941** [Cryptominer937/zPoolMiner#22]
Under settings/Device i've added only 4 Theads for CPU mining (8-4=4). This is not working. zpoolminer uses always all threads. (i7-6700k)

btw. i missing the **m7m** algo for cpu mining :)

**Comment by Cryptominer937** [comment]
yes m7m will be in the next release 1.9.0.5 was released early due to a bug in the devfee management were people were getting stuck mining the devfee.

As to the less threads option you have to set it for each algo in settings for the cpu by default it should use total threads minus one. 

Feel free to direct message me on discord Cryptominer937#0439 or twitter @MyCryptoCoinz
I would be glad to take a look over teamviewer to see what is causing this as I also am running on a I7-6700K.

**Comment by bigbear22941** [comment]
try it...  
if i set 3 less thread -> 5 running
if i set 5 less thread - > 3 running..
but when i set 4 less thread -> all 8 threads running...

**Comment by Cryptominer937** [comment]
![4 threads](https://user-images.githubusercontent.com/28938583/35867606-2075ba2e-0b28-11e8-8d4f-e38856008ad1.png)

**Comment by bigbear22941** [comment]
okay.. i have made a clean install and it works :)

thx
